### PR TITLE
fix get_line() to return a string when encountering EOF w/o newline

### LINKED ISSUE #2: get_line() doesn't return last line w/o newline
If the last line doesn't have a newline (or `\r\n`), `get_line()` will skip it.  `get_line()` is in KITTEN.C

Here is an example file where the last line "EOF (end of file).", won't be in the output.
[sudeneof.txt](https://github.com/FDOS/sort/files/5643044/sudeneof.txt)

### PR DESCRIPTION
**Pull request by micahcochran**
`get_line()` from kitten.c
Remove variables lastcr and success, neither are changing in the current implementation. 

Also, add a unit testing suite consisting of text files and a unit test Rexx script (Regina interpreter).

Fixes #2

### CODE REVIEW

**Comment by micahcochran** [comment]
Thanks.

**Comment by andrewbird** [comment]
Hi Micah,
  I'm working on splitting out kitten and setting up easy native/cross compiling etc, see https://github.com/andrewbird/sort/tree/kitten-01, I have it mostly done but I seem to have an issue with one test when the binary is built with Watcom(both native and cross). I've never used Rexx before, so I'd like to ask a few things:
- Were all 6 tests passing on your Watcom build?
- What version of Watcom were you using to build?
- Is there a way with Rexx to see what the test was objecting too?

Thanks

**Comment by andrewbird** [comment]
It's okay I found the problem, fix coming...

**Comment by micahcochran** [comment]
I was building on Watcom 2.0 Beta from October 2020 on Linux.

The Rexx testing could use some tuning to make it a little more robust.

**Pull request merged**
